energy_grid:
  target: local
  outputs:
    local:
      type: sqlite
      threads: 1
      database: energy_grid
      schema: main
      schema_directory: .
      schemas_and_paths:
        main: energy_grid.db
    aws:
      type: athena
      s3_staging_dir: s3://my-athena-bucket/staging/
      region_name: ap-southeast-2
      work_group: primary
      database: lakehouse
