global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'spark'
    static_configs:
      - targets: ['spark-exporter:5556']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:5556']
  - job_name: 'flink'
    static_configs:
      - targets: ['flink-exporter:5556']
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-exporter:9102']
