---
name: Deploy

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: ap-southeast-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        working-directory: terraform
        run: terraform fmt -check
      - name: Terraform init
        working-directory: terraform
        run: terraform init
      - name: Terraform plan
        if: github.event_name == 'pull_request'
        working-directory: terraform
        run: terraform plan -var-file=dev.tfvars
      - name: Terraform apply
        if: github.event_name == 'push'
        working-directory: terraform
        run: |
          terraform plan -out=tfplan -var-file=prod.tfvars
          terraform apply -auto-approve tfplan
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Build and push image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/flink-job:latest \
            flink_jobs
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/flink-job:latest
      - name: Sync DAGs to MWAA
        env:
          MWAA_BUCKET: ${{ secrets.MWAA_BUCKET }}
        run: |
          aws s3 sync airflow/dags s3://$MWAA_BUCKET/dags
